language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
before_script:
  - "cd docs" 
  - "npm install"
script:
  - "npm run test"
after_success:
  - "npm run deploy"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: docs/public
  target_branch: gh-pages
  keep-history: true
  on:
    branch: develop