<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" Version="4.0.1" />
    <PackageReference Include="Testcontainers.PostgreSql" Version="4.15.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Libraries\Spark.Store.PostgreSQL\Spark.Store.PostgreSQL.csproj" />
    <ProjectReference Include="..\..\Libraries\Spark.Engine.R4\Spark.Engine.R4.csproj" />
  </ItemGroup>

</Project>
